import { Form, FormResponse } from '@/types/form'
import { useMutation, useQuery } from 'convex/react'
import { api } from '@/convex/_generated/api'
import { Id } from '@/convex/_generated/dataModel'
import { useUser } from '@clerk/nextjs'

// Hook-based storage using Convex
export function useStorage() {
  const { user } = useUser()
  const userId = user?.id || ''
  
  const saveFormMutation = useMutation(api.forms.saveForm)
  const getAllFormsQuery = useQuery(
    api.forms.getAllForms, 
    userId ? { userId } : "skip"
  )
  const deleteFormMutation = useMutation(api.forms.deleteForm)
  const saveResponseMutation = useMutation(api.responses.saveResponse)
  const getAllResponsesQuery = useQuery(api.responses.getAllResponses)

  return {
    // Forms
    saveForm: async (form: Form) => {
      if (!userId) throw new Error('User not authenticated')
      
      // First, try to find existing form by title to get Convex ID
      const allForms = getAllFormsQuery || []
      const existing = allForms.find(f => f.title === form.title)
      
      if (existing) {
        // Update existing form
        const existingId = (existing as any)._id || existing.id
        await saveFormMutation({
          id: existingId,
          userId,
          title: form.title,
          description: form.description,
          isQuiz: form.isQuiz,
          timerMinutes: form.timerMinutes,
          fields: form.fields,
          createdAt: form.createdAt,
          updatedAt: form.updatedAt,
        })
        return existingId
      } else {
        // Create new form
        const formId = await saveFormMutation({
          id: '', // Will be generated by Convex
          userId,
          title: form.title,
          description: form.description,
          isQuiz: form.isQuiz,
          timerMinutes: form.timerMinutes,
          fields: form.fields,
          createdAt: form.createdAt,
          updatedAt: form.updatedAt,
        })
        return formId
      }
    },

    getForm: (id: string): Form | undefined => {
      // First try from user's forms (if signed in)
      if (userId) {
        const forms = getAllFormsQuery || []
        const found = forms.find(f => {
          const formId = (f as any)._id || f.id
          return String(formId) === String(id)
        })
        if (found) {
          const formId = (found as any)._id || found.id
          return {
            id: formId,
            title: found.title,
            description: found.description,
            isQuiz: found.isQuiz,
            timerMinutes: found.timerMinutes,
            fields: found.fields,
            createdAt: found.createdAt,
            updatedAt: found.updatedAt,
          }
        }
      }
      // For public viewing, we need to use a different approach
      // Since we can't use useQuery conditionally, we'll need to handle this in the component
      // For now, return undefined and let the component handle it
      return undefined
    },

    getAllForms: (): Form[] => {
      const forms = getAllFormsQuery || []
      return forms.map(f => {
        const formId = (f as any)._id || f.id
        return {
          id: formId,
          title: f.title,
          description: f.description,
          isQuiz: f.isQuiz,
          timerMinutes: f.timerMinutes,
          fields: f.fields,
          createdAt: f.createdAt,
          updatedAt: f.updatedAt,
        }
      })
    },

    deleteForm: async (id: string) => {
      if (!userId) throw new Error('User not authenticated')
      await deleteFormMutation({ id: id as Id<"forms">, userId })
    },

    // Responses
    saveResponse: async (response: FormResponse) => {
      // The formId should already be a Convex ID string
      // Try to use it directly, or find from user's forms as fallback
      let convexFormId: Id<"forms">
      
      // Try to use formId directly (it should be a Convex ID)
      if (response.formId && typeof response.formId === 'string') {
        convexFormId = response.formId as Id<"forms">
      } else {
        // Fallback: find from user's forms
        const allForms = getAllFormsQuery || []
        const form = allForms.find(f => {
          const fId = (f as any)._id || f.id
          return String(fId) === String(response.formId)
        })
        
        if (!form) {
          console.error('Form not found for response:', response.formId)
          return
        }
        convexFormId = (form as any)._id || form.id
      }

      await saveResponseMutation({
        formId: convexFormId,
        responses: response.responses,
        submittedAt: response.submittedAt,
        score: response.score,
        maxScore: response.maxScore,
        answers: response.answers,
        studentName: response.studentName,
        studentClass: response.studentClass,
      })
    },

    getResponses: (formId: string): FormResponse[] => {
      // Need to convert string formId to Convex Id
      const allForms = getAllFormsQuery || []
      const form = allForms.find(f => {
        const fId = (f as any)._id || f.id
        return fId === formId || String(fId) === String(formId) || f.title === formId
      })
      
      if (!form) return []
      
      // Filter from getAllResponses instead of using getResponses query
      // This avoids the issue of calling useQuery with required args
      const allResponses = getAllResponsesQuery || []
      const convexFormId = (form as any)._id || form.id
      const responses = allResponses.filter(r => {
        const rFormId = (r as any).formId
        return String(rFormId) === String(convexFormId)
      })
      
      return responses.map(r => ({
        id: (r as any)._id || r.id,
        formId: r.formId,
        responses: r.responses,
        submittedAt: r.submittedAt,
        score: r.score,
        maxScore: r.maxScore,
        answers: r.answers,
        studentName: r.studentName,
        studentClass: r.studentClass,
      }))
    },

    getAllResponses: (): FormResponse[] => {
      const responses = getAllResponsesQuery || []
      return responses.map(r => ({
        id: (r as any)._id || r.id,
        formId: r.formId,
        responses: r.responses,
        submittedAt: r.submittedAt,
        score: r.score,
        maxScore: r.maxScore,
        answers: r.answers,
        studentName: r.studentName,
        studentClass: r.studentClass,
      }))
    },
  }
}
